// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJBu_C8kkJuCk-1vph6GA-NhI8Dfzpkbk',
    appId: '1:6014627653:web:8e5cac8fba83cb3403982c',
    messagingSenderId: '6014627653',
    projectId: 'chatdemoapp-57cc6',
    authDomain: 'chatdemoapp-57cc6.firebaseapp.com',
    databaseURL: 'https://chatdemoapp-57cc6-default-rtdb.firebaseio.com',
    storageBucket: 'chatdemoapp-57cc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDWUIeoliGcLumxcs5UZ-B_woQJAtV3ok',
    appId: '1:6014627653:android:c750939bfa25721703982c',
    messagingSenderId: '6014627653',
    projectId: 'chatdemoapp-57cc6',
    databaseURL: 'https://chatdemoapp-57cc6-default-rtdb.firebaseio.com',
    storageBucket: 'chatdemoapp-57cc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWe8w2K58eyo-wNdy1GqzyWaUihwk0V2A',
    appId: '1:6014627653:ios:797a58a51769afba03982c',
    messagingSenderId: '6014627653',
    projectId: 'chatdemoapp-57cc6',
    databaseURL: 'https://chatdemoapp-57cc6-default-rtdb.firebaseio.com',
    storageBucket: 'chatdemoapp-57cc6.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
